name: Build and Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build project
        env:
          CI: ""
        run: npm run build

      - name: Gather required files
        run: |
            mkdir tempdir;                         \
            mv ./package.json ./tempdir/;          \
            mv ./build ./tempdir/;                 \
            mv ./climate.conf.js ./tempdir/;       \
            mv ./freya-core.conf ./tempdir/;       \
            mv ./io.freya.Core.service ./tempdir/; \
            mv ./uninstall.sh ./tempdir;
      
      - name: Download latest UI release asset
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh release download --repo Freya-Vivariums/Freya-core-ui --pattern "Freya-core-ui.tar.gz"

      - name: Unpack the UI in the public folder
        run: |
          rm -rf ./tempdir/build/public/*                                        \
          tar -xzf Edgeberry-dashboard-UI.tar.gz -C ./tempdir/build/public

      - name: Create tarball
        run: tar -C ./tempdir -zcvf package.tar.gz .

      - name: Get Project Name
        id: project_name
        run: echo "::set-output name=name::$(echo ${{ github.repository }} | cut -d'/' -f2)"

      - name: Upload packaged project build to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: package.tar.gz
          asset_name: ${{ steps.project_name.outputs.name }}-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload install script to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: install.sh
          asset_name: install.sh
          asset_content_type: application/octet-stream